name: aio_image_provider
description: "A Flutter package that provide utility for image, image search, and image picker"
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.1.9
  uuid: ^4.5.1
  http: ^1.4.0
  path_provider: ^2.1.5
  crypto: ^3.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_lints: ^5.0.0

